(emux-session-set-default-directory "~/projects/thoughtstream-user_management")
(emux-screen-create '(:name "guard") "guard" "bundle exec guard --notify false")
;;(emux-screen-create '(:name "rc") "rc" "rc")
(emux-screen-create '(:name "tail" :no-terminal t))
(itail "log/development.log")
